using System;
using System.Collections.Generic;
using MoreSlugcats;
using UnityEngine;

public static class LizardBreeds
{
	static LizardBreeds()
	{
	}

	public static CreatureTemplate BreedTemplate(CreatureTemplate.Type type, CreatureTemplate lizardAncestor, CreatureTemplate pinkTemplate, CreatureTemplate blueTemplate, CreatureTemplate greenTemplate)
	{
		List<TileTypeResistance> list = new List<TileTypeResistance>();
		List<TileConnectionResistance> list2 = new List<TileConnectionResistance>();
		LizardBreedParams lizardBreedParams = new LizardBreedParams(type);
		lizardBreedParams.terrainSpeeds = new LizardBreedParams.SpeedMultiplier[Enum.GetNames(typeof(AItile.Accessibility)).Length];
		for (int i = 0; i < lizardBreedParams.terrainSpeeds.Length; i++)
		{
			lizardBreedParams.terrainSpeeds[i] = new LizardBreedParams.SpeedMultiplier(0.1f, 1f, 1f, 1f);
		}
		lizardBreedParams.bodyRadFac = 1f;
		lizardBreedParams.pullDownFac = 1f;
		lizardBreedParams.bodyLengthFac = 1f;
		bool flag = false;
		float visualRadius = 0f;
		float waterVision = 0f;
		float throughSurfaceVision = 0f;
		float movementBasedVision = 0.3f;
		float waterPathingResistance = 3f;
		if (type == CreatureTemplate.Type.PinkLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1.2f, 1f, 0.8f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 2.5f, PathCost.Legality.Allowed));
			waterPathingResistance = 3f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 40f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 12;
			lizardBreedParams.biteInFront = 25f;
			lizardBreedParams.biteHomingSpeed = 1.7f;
			lizardBreedParams.biteChance = 0.5f;
			lizardBreedParams.attemptBiteRadius = 80f;
			lizardBreedParams.getFreeBiteChance = 0.65f;
			lizardBreedParams.biteDamage = 1f;
			lizardBreedParams.biteDamageChance = 1f / 3f;
			lizardBreedParams.toughness = 1f;
			lizardBreedParams.stunToughness = 1f;
			lizardBreedParams.regainFootingCounter = 10;
			lizardBreedParams.baseSpeed = 4.1f;
			lizardBreedParams.bodyMass = 2.1f;
			lizardBreedParams.bodySizeFac = 1f;
			lizardBreedParams.floorLeverage = 0.5f;
			lizardBreedParams.maxMusclePower = 5f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.2f;
			lizardBreedParams.swimSpeed = 0.2f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.danger = 0.45f;
			lizardBreedParams.aggressionCurveExponent = 0.9f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 900f;
			waterVision = 0.4f;
			throughSurfaceVision = 0.85f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 7f / 12f);
			lizardBreedParams.biteDominance = 0.5f;
			lizardBreedParams.limbSize = 1f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.5f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 5f;
			lizardBreedParams.limbQuickness = 0.5f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(1f, 0f, 1f);
			lizardBreedParams.walkBob = 4f;
			lizardBreedParams.tailSegments = 5;
			lizardBreedParams.tailStiffness = 250f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 1f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 90f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 80;
			lizardBreedParams.tamingDifficulty = 1f;
		}
		else if (type == CreatureTemplate.Type.GreenLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 0.8f, 1.7f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(0.8f, 1f, 0.8f, 1.7f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 2f, PathCost.Legality.Allowed));
			waterPathingResistance = 1.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 40f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.LizardTurn, 60f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 20;
			lizardBreedParams.biteInFront = 40f;
			lizardBreedParams.biteHomingSpeed = 0.7f;
			lizardBreedParams.biteChance = 1f / 3f;
			lizardBreedParams.attemptBiteRadius = 100f;
			lizardBreedParams.getFreeBiteChance = 0.45f;
			lizardBreedParams.biteDamage = 2f;
			lizardBreedParams.biteDamageChance = 0.5f;
			lizardBreedParams.toughness = 2.5f;
			lizardBreedParams.stunToughness = 1.5f;
			lizardBreedParams.regainFootingCounter = 10;
			lizardBreedParams.baseSpeed = 6.7f;
			lizardBreedParams.bodyMass = 7.5f;
			lizardBreedParams.bodySizeFac = 1.2f;
			lizardBreedParams.floorLeverage = 7f;
			lizardBreedParams.maxMusclePower = 16f;
			lizardBreedParams.danger = 0.45f;
			lizardBreedParams.aggressionCurveExponent = 0.95f;
			lizardBreedParams.wiggleSpeed = 0f;
			lizardBreedParams.wiggleDelay = 55;
			lizardBreedParams.bodyStiffnes = 0.5f;
			lizardBreedParams.swimSpeed = 0.6f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.biteDominance = 0.8f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = false;
			lizardBreedParams.findLoungeDirection = 0f;
			lizardBreedParams.loungeDistance = 170f;
			lizardBreedParams.preLoungeCrouch = 50;
			lizardBreedParams.preLoungeCrouchMovement = -0.3f;
			lizardBreedParams.loungeSpeed = 1f;
			lizardBreedParams.loungeMaximumFrames = 40;
			lizardBreedParams.loungePropulsionFrames = 40;
			lizardBreedParams.loungeJumpyness = 0f;
			lizardBreedParams.loungeDelay = 150;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.3f;
			lizardBreedParams.postLoungeStun = 40;
			lizardBreedParams.loungeTendensy = 1f;
			visualRadius = 850f;
			waterVision = 0.3f;
			throughSurfaceVision = 0.85f;
			movementBasedVision = 0.7f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 5f / 18f);
			lizardBreedParams.limbSize = 1.4f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.9f;
			lizardBreedParams.liftFeet = 0.5f;
			lizardBreedParams.feetDown = 1f;
			lizardBreedParams.noGripSpeed = 0.05f;
			lizardBreedParams.limbSpeed = 3f;
			lizardBreedParams.limbQuickness = 0.3f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = false;
			lizardBreedParams.legPairDisplacement = 1f;
			lizardBreedParams.standardColor = new Color(0.2f, 1f, 0f);
			lizardBreedParams.walkBob = 4f;
			lizardBreedParams.tailSegments = 7;
			lizardBreedParams.tailStiffness = 300f;
			lizardBreedParams.tailStiffnessDecline = 0.6f;
			lizardBreedParams.tailLengthFactor = 0.9f;
			lizardBreedParams.tailColorationStart = 0.05f;
			lizardBreedParams.tailColorationExponent = 4f;
			lizardBreedParams.headSize = 1f;
			lizardBreedParams.neckStiffness = 1f;
			lizardBreedParams.jawOpenAngle = 50f;
			lizardBreedParams.jawOpenLowerJawFac = 0.5f;
			lizardBreedParams.jawOpenMoveJawsApart = 14f;
			lizardBreedParams.headGraphics = new int[5] { 1, 1, 1, 1, 1 };
			lizardBreedParams.framesBetweenLookFocusChange = 160;
			lizardBreedParams.tamingDifficulty = 0.8f;
		}
		else if (type == CreatureTemplate.Type.BlueLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1.2f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 0.8f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[4] = new LizardBreedParams.SpeedMultiplier(0.8f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Wall, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[5] = new LizardBreedParams.SpeedMultiplier(0.6f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Ceiling, 1.2f, PathCost.Legality.Allowed));
			waterPathingResistance = 5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 20f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 2f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ShortCut, 15f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachOverGap, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachUp, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachDown, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.CeilingSlope, 2f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 14;
			lizardBreedParams.biteInFront = 20f;
			lizardBreedParams.biteHomingSpeed = 1.4f;
			lizardBreedParams.biteChance = 0.4f;
			lizardBreedParams.attemptBiteRadius = 90f;
			lizardBreedParams.getFreeBiteChance = 0.5f;
			lizardBreedParams.biteDamage = 0.7f;
			lizardBreedParams.biteDamageChance = 0.2f;
			lizardBreedParams.toughness = 0.5f;
			lizardBreedParams.stunToughness = 0.75f;
			lizardBreedParams.regainFootingCounter = 4;
			lizardBreedParams.baseSpeed = 3.2f;
			lizardBreedParams.bodyMass = 1.4f;
			lizardBreedParams.bodySizeFac = 0.9f;
			lizardBreedParams.floorLeverage = 1f;
			lizardBreedParams.maxMusclePower = 2f;
			lizardBreedParams.danger = 0.35f;
			lizardBreedParams.aggressionCurveExponent = 0.875f;
			lizardBreedParams.wiggleSpeed = 1f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0f;
			lizardBreedParams.swimSpeed = 0.35f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = true;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 1f;
			lizardBreedParams.loungeDistance = 80f;
			lizardBreedParams.preLoungeCrouch = 35;
			lizardBreedParams.preLoungeCrouchMovement = -0.3f;
			lizardBreedParams.loungeSpeed = 2.5f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 8;
			lizardBreedParams.loungeJumpyness = 0.9f;
			lizardBreedParams.loungeDelay = 310;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.8f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.01f;
			visualRadius = 950f;
			waterVision = 0.4f;
			throughSurfaceVision = 0.85f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 1f / 18f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 11f / 24f);
			lizardBreedParams.biteDominance = 0.1f;
			lizardBreedParams.limbSize = 0.9f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.4f;
			lizardBreedParams.liftFeet = 0f;
			lizardBreedParams.feetDown = 0f;
			lizardBreedParams.noGripSpeed = 0.2f;
			lizardBreedParams.limbSpeed = 6f;
			lizardBreedParams.limbQuickness = 0.6f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0f;
			lizardBreedParams.standardColor = new Color(0f, 0.5f, 1f);
			lizardBreedParams.walkBob = 0.4f;
			lizardBreedParams.tailSegments = 4;
			lizardBreedParams.tailStiffness = 400f;
			lizardBreedParams.tailStiffnessDecline = 0.1f;
			lizardBreedParams.tailLengthFactor = 1f;
			lizardBreedParams.tailColorationStart = 0.1f;
			lizardBreedParams.tailColorationExponent = 1.2f;
			lizardBreedParams.headSize = 0.9f;
			lizardBreedParams.neckStiffness = 0f;
			lizardBreedParams.jawOpenAngle = 105f;
			lizardBreedParams.jawOpenLowerJawFac = 0.55f;
			lizardBreedParams.jawOpenMoveJawsApart = 20f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 20;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 140f;
			lizardBreedParams.tongueWarmUp = 10;
			lizardBreedParams.tongueSegments = 5;
			lizardBreedParams.tongueChance = 0.25f;
			lizardBreedParams.tamingDifficulty = 1.1f;
		}
		else if (type == CreatureTemplate.Type.YellowLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1.2f, 1f, 0.8f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 2.5f, PathCost.Legality.Allowed));
			waterPathingResistance = 2.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 4f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 8f, PathCost.Legality.Allowed));
			flag = true;
			lizardBreedParams.biteDelay = 21;
			lizardBreedParams.biteInFront = 15f;
			lizardBreedParams.biteHomingSpeed = 1.2f;
			lizardBreedParams.biteChance = 1f / 6f;
			lizardBreedParams.attemptBiteRadius = 40f;
			lizardBreedParams.getFreeBiteChance = 0.65f;
			lizardBreedParams.biteDamage = 0.8f;
			lizardBreedParams.biteDamageChance = 0.25f;
			lizardBreedParams.toughness = 0.8f;
			lizardBreedParams.stunToughness = 1f;
			lizardBreedParams.regainFootingCounter = 10;
			lizardBreedParams.baseSpeed = 4.1f;
			lizardBreedParams.bodyMass = 1.7f;
			lizardBreedParams.bodySizeFac = 0.93f;
			lizardBreedParams.floorLeverage = 0.5f;
			lizardBreedParams.maxMusclePower = 5f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.2f;
			lizardBreedParams.swimSpeed = 0.3f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.danger = 0.4f;
			lizardBreedParams.aggressionCurveExponent = 0.77f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 900f;
			waterVision = 0.35f;
			throughSurfaceVision = 0.85f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 1f / 12f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 19f / 36f);
			lizardBreedParams.biteDominance = 0.45f;
			lizardBreedParams.limbSize = 1f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.5f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 5f;
			lizardBreedParams.limbQuickness = 0.5f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(1f, 0.6f, 0f);
			lizardBreedParams.walkBob = 4f;
			lizardBreedParams.tailSegments = 5;
			lizardBreedParams.tailStiffness = 250f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 1f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 90f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 80;
			lizardBreedParams.tamingDifficulty = 3f;
		}
		else if (type == CreatureTemplate.Type.WhiteLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1.2f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 0.8f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[4] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Wall, 1f, PathCost.Legality.Allowed));
			waterPathingResistance = 8f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 10f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 10f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ShortCut, 2f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachOverGap, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachUp, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachDown, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.CeilingSlope, 20f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 15;
			lizardBreedParams.biteInFront = 25f;
			lizardBreedParams.biteHomingSpeed = 1.7f;
			lizardBreedParams.biteChance = 0.5f;
			lizardBreedParams.attemptBiteRadius = 85f;
			lizardBreedParams.getFreeBiteChance = 0.7f;
			lizardBreedParams.biteDamage = 1f;
			lizardBreedParams.biteDamageChance = 0.2857143f;
			lizardBreedParams.toughness = 0.9f;
			lizardBreedParams.stunToughness = 1.1f;
			lizardBreedParams.regainFootingCounter = 5;
			lizardBreedParams.baseSpeed = 3.8f;
			lizardBreedParams.bodyMass = 2.1f;
			lizardBreedParams.bodySizeFac = 1f;
			lizardBreedParams.floorLeverage = 0.3f;
			lizardBreedParams.maxMusclePower = 5f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.15f;
			lizardBreedParams.swimSpeed = 0.25f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.danger = 0.5f;
			lizardBreedParams.aggressionCurveExponent = 0.95f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 1300f;
			waterVision = 0.4f;
			throughSurfaceVision = 0.9f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 1f / 6f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 19f / 36f);
			lizardBreedParams.biteDominance = 0.5f;
			lizardBreedParams.limbSize = 1f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.6f;
			lizardBreedParams.liftFeet = 0.2f;
			lizardBreedParams.feetDown = 0.05f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 8f;
			lizardBreedParams.limbQuickness = 0.8f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = false;
			lizardBreedParams.legPairDisplacement = 0f;
			lizardBreedParams.standardColor = new Color(1f, 1f, 1f);
			lizardBreedParams.walkBob = 0.8f;
			lizardBreedParams.tailSegments = 5;
			lizardBreedParams.tailStiffness = 800f;
			lizardBreedParams.tailStiffnessDecline = 0.1f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.1f;
			lizardBreedParams.tailColorationExponent = 1.2f;
			lizardBreedParams.headSize = 1f;
			lizardBreedParams.neckStiffness = 0.05f;
			lizardBreedParams.jawOpenAngle = 110f;
			lizardBreedParams.jawOpenLowerJawFac = 0.5f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5] { 0, 0, 0, 0, 3 };
			lizardBreedParams.framesBetweenLookFocusChange = 180;
			lizardBreedParams.tamingDifficulty = 3f;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 440f;
			lizardBreedParams.tongueWarmUp = 80;
			lizardBreedParams.tongueSegments = 10;
			lizardBreedParams.tongueChance = 0.1f;
		}
		else if (type == CreatureTemplate.Type.RedLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 0.9f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.9f, 1f, 0.6f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 1f, PathCost.Legality.Allowed));
			waterPathingResistance = 2f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 4f, PathCost.Legality.Allowed));
			flag = true;
			lizardBreedParams.biteDelay = 2;
			lizardBreedParams.biteInFront = 20f;
			lizardBreedParams.biteRadBonus = ((ModManager.MMF && MMF.cfgAlphaRedLizards.Value) ? 5f : 25f);
			lizardBreedParams.biteHomingSpeed = 4.7f;
			lizardBreedParams.biteChance = 1f;
			lizardBreedParams.attemptBiteRadius = 120f;
			lizardBreedParams.getFreeBiteChance = 1f;
			lizardBreedParams.biteDamage = 4f;
			lizardBreedParams.biteDamageChance = 1f;
			lizardBreedParams.toughness = 3f;
			lizardBreedParams.stunToughness = 3f;
			lizardBreedParams.regainFootingCounter = 1;
			lizardBreedParams.baseSpeed = 5f;
			lizardBreedParams.bodyMass = 3.1f;
			lizardBreedParams.bodySizeFac = 1.2f;
			lizardBreedParams.floorLeverage = 6f;
			lizardBreedParams.maxMusclePower = 9f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.3f;
			lizardBreedParams.swimSpeed = 1.9f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 10;
			lizardBreedParams.danger = 0.8f;
			lizardBreedParams.aggressionCurveExponent = 0.7f;
			lizardBreedParams.headShieldAngle = 100f;
			if (ModManager.MMF && MMF.cfgAlphaRedLizards.Value)
			{
				lizardBreedParams.tongue = true;
				lizardBreedParams.tongueAttackRange = 350f;
				lizardBreedParams.tongueWarmUp = 8;
				lizardBreedParams.tongueSegments = 10;
				lizardBreedParams.tongueChance = 0.1f;
			}
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 2300f;
			waterVision = 0.7f;
			throughSurfaceVision = 0.95f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 4f / 9f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 7f / 9f);
			lizardBreedParams.biteDominance = 1f;
			lizardBreedParams.limbSize = 1.5f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.8f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.25f;
			lizardBreedParams.limbSpeed = 9f;
			lizardBreedParams.limbQuickness = 0.8f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(1f, 0f, 0f);
			lizardBreedParams.walkBob = 3f;
			lizardBreedParams.tailSegments = 11;
			lizardBreedParams.tailStiffness = 200f;
			lizardBreedParams.tailStiffnessDecline = 0.3f;
			lizardBreedParams.tailLengthFactor = 1.9f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 1.2f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 140f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 20;
			lizardBreedParams.tamingDifficulty = 7f;
		}
		else if (type == CreatureTemplate.Type.BlackLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1.2f, 1f, 0.8f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 2.5f, PathCost.Legality.Allowed));
			waterPathingResistance = 3.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 40f, PathCost.Legality.Allowed));
			flag = true;
			lizardBreedParams.biteDelay = 12;
			lizardBreedParams.biteInFront = 26f;
			lizardBreedParams.biteHomingSpeed = 1.6f;
			lizardBreedParams.biteChance = 1f / 3f;
			lizardBreedParams.attemptBiteRadius = 70f;
			lizardBreedParams.getFreeBiteChance = 0.65f;
			lizardBreedParams.biteDamage = 1f;
			lizardBreedParams.biteDamageChance = 5f / 14f;
			lizardBreedParams.toughness = 1f;
			lizardBreedParams.stunToughness = 1f;
			lizardBreedParams.regainFootingCounter = 8;
			lizardBreedParams.baseSpeed = 3.9f;
			lizardBreedParams.bodyMass = 2f;
			lizardBreedParams.bodySizeFac = 0.9f;
			lizardBreedParams.floorLeverage = 0.35f;
			lizardBreedParams.maxMusclePower = 4.8f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.25f;
			lizardBreedParams.swimSpeed = 0.2f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.danger = 0.45f;
			lizardBreedParams.aggressionCurveExponent = 0.825f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 0f;
			waterVision = 0f;
			throughSurfaceVision = 0f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 0f);
			lizardBreedParams.biteDominance = 0.5f;
			lizardBreedParams.limbSize = 1.1f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.6f;
			lizardBreedParams.liftFeet = 0.25f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 5f;
			lizardBreedParams.limbQuickness = 0.6f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(0.1f, 0.1f, 0.1f);
			lizardBreedParams.walkBob = 3f;
			lizardBreedParams.tailSegments = 6;
			lizardBreedParams.tailStiffness = 300f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 1f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 90f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 100;
			lizardBreedParams.tamingDifficulty = 4f;
		}
		else if (type == CreatureTemplate.Type.Salamander)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1.2f, 1f, 0.8f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 2.5f, PathCost.Legality.Allowed));
			waterPathingResistance = 0.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 40f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 12;
			lizardBreedParams.biteInFront = 20f;
			lizardBreedParams.biteHomingSpeed = 1.6f;
			lizardBreedParams.biteChance = 1f / 3f;
			lizardBreedParams.attemptBiteRadius = 70f;
			lizardBreedParams.getFreeBiteChance = 0.65f;
			lizardBreedParams.biteDamage = 0.9f;
			lizardBreedParams.biteDamageChance = 1f / 3f;
			lizardBreedParams.toughness = 1f;
			lizardBreedParams.stunToughness = 0.9f;
			lizardBreedParams.regainFootingCounter = 10;
			lizardBreedParams.baseSpeed = 3.1f;
			lizardBreedParams.bodyMass = 2.1f;
			lizardBreedParams.bodySizeFac = 0.9f;
			lizardBreedParams.floorLeverage = 0.1f;
			lizardBreedParams.maxMusclePower = 5f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.2f;
			lizardBreedParams.swimSpeed = 0.2f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 100;
			lizardBreedParams.danger = 0.4f;
			lizardBreedParams.aggressionCurveExponent = 0.875f;
			lizardBreedParams.headShieldAngle = 70f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 100f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 1.9f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.05f;
			visualRadius = 960f;
			waterVision = 1f;
			throughSurfaceVision = 0.5f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 31f / 36f);
			lizardBreedParams.biteDominance = 0.3f;
			lizardBreedParams.limbSize = 0.65f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.5f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 5f;
			lizardBreedParams.limbQuickness = 0.5f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = false;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(1f, 1f, 1f);
			lizardBreedParams.walkBob = 4f;
			lizardBreedParams.tailSegments = 5;
			lizardBreedParams.tailStiffness = 250f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 0.9f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 90f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 15f;
			lizardBreedParams.headGraphics = new int[5] { 2, 2, 2, 2, 2 };
			lizardBreedParams.framesBetweenLookFocusChange = 80;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 150f;
			lizardBreedParams.tongueWarmUp = 8;
			lizardBreedParams.tongueSegments = 7;
			lizardBreedParams.tongueChance = 1f / 3f;
			lizardBreedParams.tamingDifficulty = 3.5f;
		}
		else if (type == CreatureTemplate.Type.CyanLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1.2f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 0.8f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[4] = new LizardBreedParams.SpeedMultiplier(0.8f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Wall, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[5] = new LizardBreedParams.SpeedMultiplier(0.6f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Ceiling, 1.2f, PathCost.Legality.Allowed));
			waterPathingResistance = 5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 2f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 2f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ShortCut, 5f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachOverGap, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachUp, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.ReachDown, 1.1f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.CeilingSlope, 2f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 12;
			lizardBreedParams.biteInFront = 25f;
			lizardBreedParams.biteHomingSpeed = 1.4f;
			lizardBreedParams.biteChance = 0.46511626f;
			lizardBreedParams.attemptBiteRadius = 90f;
			lizardBreedParams.getFreeBiteChance = 0.72f;
			lizardBreedParams.biteDamage = 1f;
			lizardBreedParams.biteDamageChance = 1f / 3f;
			lizardBreedParams.toughness = 0.9f;
			lizardBreedParams.stunToughness = 0.8f;
			lizardBreedParams.regainFootingCounter = 3;
			lizardBreedParams.baseSpeed = 4.85f;
			lizardBreedParams.bodyMass = 2f;
			lizardBreedParams.bodySizeFac = 1f;
			lizardBreedParams.floorLeverage = 0.5f;
			lizardBreedParams.maxMusclePower = 4f;
			lizardBreedParams.danger = 0.65f;
			lizardBreedParams.aggressionCurveExponent = 0.9f;
			lizardBreedParams.wiggleSpeed = 1f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0f;
			lizardBreedParams.swimSpeed = 0.45f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 1;
			lizardBreedParams.headShieldAngle = 35f;
			lizardBreedParams.canExitLounge = true;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 1f;
			lizardBreedParams.loungeDistance = 130f;
			lizardBreedParams.preLoungeCrouch = 35;
			lizardBreedParams.preLoungeCrouchMovement = -0.3f;
			lizardBreedParams.loungeSpeed = 4.5f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.9f;
			lizardBreedParams.loungeDelay = 110;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.8f;
			lizardBreedParams.postLoungeStun = 10;
			lizardBreedParams.loungeTendensy = 1f / 30f;
			visualRadius = 990f;
			waterVision = 0.4f;
			throughSurfaceVision = 0.85f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 1f / 12f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 11f / 24f);
			lizardBreedParams.biteDominance = 0.3f;
			lizardBreedParams.limbSize = 1f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.4f;
			lizardBreedParams.liftFeet = 0f;
			lizardBreedParams.feetDown = 0f;
			lizardBreedParams.noGripSpeed = 0.2f;
			lizardBreedParams.limbSpeed = 6f;
			lizardBreedParams.limbQuickness = 0.6f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0f;
			lizardBreedParams.standardColor = new Color(0f, 1f, 0.9f);
			lizardBreedParams.walkBob = 2f;
			lizardBreedParams.tailSegments = 6;
			lizardBreedParams.tailStiffness = 250f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.8f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 0.95f;
			lizardBreedParams.neckStiffness = 0.8f;
			lizardBreedParams.jawOpenAngle = 110f;
			lizardBreedParams.jawOpenLowerJawFac = 0.55f;
			lizardBreedParams.jawOpenMoveJawsApart = 22f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 80;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 160f;
			lizardBreedParams.tongueWarmUp = 8;
			lizardBreedParams.tongueSegments = 7;
			lizardBreedParams.tongueChance = 1f / 3f;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.SpitLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(3f, 3f, 0.8f, 2f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(2f, 0.9f, 1.4f, 1.9f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 2f, PathCost.Legality.Allowed));
			waterPathingResistance = 1.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 40f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.LizardTurn, 60f, PathCost.Legality.Allowed));
			lizardBreedParams.biteDelay = 6;
			lizardBreedParams.biteInFront = 15f;
			lizardBreedParams.biteHomingSpeed = 1.4f;
			lizardBreedParams.biteChance = 0.46511626f;
			lizardBreedParams.attemptBiteRadius = 90f;
			lizardBreedParams.getFreeBiteChance = 0.72f;
			lizardBreedParams.biteDamage = 1.2f;
			lizardBreedParams.biteDamageChance = 0.5f;
			lizardBreedParams.toughness = 2.5f;
			lizardBreedParams.stunToughness = 1.5f;
			lizardBreedParams.regainFootingCounter = 10;
			lizardBreedParams.baseSpeed = 0.65f;
			lizardBreedParams.bodyMass = 4f;
			lizardBreedParams.bodySizeFac = 1.75f;
			lizardBreedParams.floorLeverage = 0.2f;
			lizardBreedParams.maxMusclePower = 3f;
			lizardBreedParams.danger = 0.8f;
			lizardBreedParams.aggressionCurveExponent = 0.95f;
			lizardBreedParams.wiggleSpeed = 0f;
			lizardBreedParams.wiggleDelay = 55;
			lizardBreedParams.bodyStiffnes = 0.2f;
			lizardBreedParams.swimSpeed = 0.45f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.biteDominance = 0.4f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = false;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 400f;
			lizardBreedParams.preLoungeCrouch = 40;
			lizardBreedParams.preLoungeCrouchMovement = -0.2f;
			lizardBreedParams.loungeSpeed = 4.5f;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 2f;
			lizardBreedParams.loungeDelay = 200;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			lizardBreedParams.postLoungeStun = 70;
			lizardBreedParams.loungeTendensy = 0.85f;
			visualRadius = 2300f;
			waterVision = 0.7f;
			throughSurfaceVision = 0.95f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 4f / 9f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 7f / 9f);
			lizardBreedParams.biteDominance = 0.45f;
			lizardBreedParams.limbSize = 1.1f;
			lizardBreedParams.limbThickness = 1.5f;
			lizardBreedParams.stepLength = 0.5f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 5f;
			lizardBreedParams.limbQuickness = 0.5f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.standardColor = new Color(0.55f, 0.4f, 0.2f);
			lizardBreedParams.walkBob = 4f;
			lizardBreedParams.tailSegments = 4;
			lizardBreedParams.tailStiffness = 250f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.2f;
			lizardBreedParams.tailColorationStart = 0.3f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 1.2f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 90f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5] { 1, 1, 1, 1, 1 };
			lizardBreedParams.framesBetweenLookFocusChange = 160;
			lizardBreedParams.tamingDifficulty = 0.3f;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.ZoopLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 4f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1.2f, 1f, 0.8f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 0.2f, PathCost.Legality.Allowed));
			waterPathingResistance = 6.5f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 10f, PathCost.Legality.Allowed));
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 0.2f, PathCost.Legality.Allowed));
			flag = true;
			lizardBreedParams.biteDelay = 18;
			lizardBreedParams.biteInFront = 15f;
			lizardBreedParams.biteHomingSpeed = 4f;
			lizardBreedParams.biteChance = 0.31f;
			lizardBreedParams.attemptBiteRadius = 80f;
			lizardBreedParams.getFreeBiteChance = 0.85f;
			lizardBreedParams.biteDamage = 0.18f;
			lizardBreedParams.biteDamageChance = 0.65f;
			lizardBreedParams.toughness = 1.2f;
			lizardBreedParams.stunToughness = 0.3f;
			lizardBreedParams.regainFootingCounter = 70;
			lizardBreedParams.baseSpeed = 5.1f;
			lizardBreedParams.bodyMass = 1.4f;
			lizardBreedParams.bodySizeFac = 0.74f;
			lizardBreedParams.floorLeverage = 0.25f;
			lizardBreedParams.maxMusclePower = 9f;
			lizardBreedParams.wiggleSpeed = 0.8f;
			lizardBreedParams.wiggleDelay = 7;
			lizardBreedParams.bodyStiffnes = 0.32f;
			lizardBreedParams.swimSpeed = 0.3f;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 0;
			lizardBreedParams.danger = 0.8f;
			lizardBreedParams.aggressionCurveExponent = 0.37f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = true;
			lizardBreedParams.canExitLoungeWarmUp = false;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.loungeDistance = 60f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.preLoungeCrouchMovement = -0.7f;
			lizardBreedParams.loungeSpeed = 3.1f;
			lizardBreedParams.loungeMaximumFrames = 24;
			lizardBreedParams.loungePropulsionFrames = 5;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.loungeDelay = 90;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.4f;
			lizardBreedParams.postLoungeStun = 20;
			lizardBreedParams.loungeTendensy = 0.1f;
			visualRadius = 1400f;
			waterVision = 0.25f;
			throughSurfaceVision = 0.55f;
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 1f / 12f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 19f / 36f);
			lizardBreedParams.biteDominance = 0.15f;
			lizardBreedParams.limbSize = 0.9f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.8f;
			lizardBreedParams.liftFeet = 0.6f;
			lizardBreedParams.feetDown = 0.2f;
			lizardBreedParams.noGripSpeed = 0.1f;
			lizardBreedParams.limbSpeed = 9f;
			lizardBreedParams.limbQuickness = 0.2f;
			lizardBreedParams.limbGripDelay = 3;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.8f;
			lizardBreedParams.standardColor = new Color(0.95f, 0.73f, 0.73f);
			lizardBreedParams.walkBob = 9f;
			lizardBreedParams.tailSegments = 4;
			lizardBreedParams.tailStiffness = 20f;
			lizardBreedParams.tailStiffnessDecline = 0.2f;
			lizardBreedParams.tailLengthFactor = 1.8f;
			lizardBreedParams.tailColorationStart = 0.8f;
			lizardBreedParams.tailColorationExponent = 2f;
			lizardBreedParams.headSize = 0.9f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenAngle = 80f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 130;
			lizardBreedParams.tamingDifficulty = 2f;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 440f;
			lizardBreedParams.tongueWarmUp = 140;
			lizardBreedParams.tongueSegments = 10;
			lizardBreedParams.tongueChance = 0.3f;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.TrainLizard)
		{
			lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 0.9f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
			lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.9f, 1f, 0.6f, 1f);
			list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 1f, PathCost.Legality.Allowed));
			waterPathingResistance = 2f;
			list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 4f, PathCost.Legality.Allowed));
			flag = true;
			lizardBreedParams.biteInFront = 20f;
			lizardBreedParams.biteRadBonus = 5f;
			lizardBreedParams.biteChance = 1f;
			lizardBreedParams.getFreeBiteChance = 1f;
			lizardBreedParams.biteDamageChance = 1f;
			lizardBreedParams.regainFootingCounter = 1;
			lizardBreedParams.floorLeverage = 6f;
			lizardBreedParams.wiggleSpeed = 0.5f;
			lizardBreedParams.wiggleDelay = 15;
			lizardBreedParams.bodyStiffnes = 0.3f;
			lizardBreedParams.aggressionCurveExponent = 0.7f;
			lizardBreedParams.headShieldAngle = 100f;
			lizardBreedParams.canExitLounge = false;
			lizardBreedParams.canExitLoungeWarmUp = true;
			lizardBreedParams.findLoungeDirection = 0.5f;
			lizardBreedParams.preLoungeCrouch = 25;
			lizardBreedParams.loungeMaximumFrames = 20;
			lizardBreedParams.loungePropulsionFrames = 10;
			lizardBreedParams.loungeJumpyness = 0.5f;
			lizardBreedParams.riskOfDoubleLoungeDelay = 0.1f;
			visualRadius = 2300f;
			waterVision = 0.7f;
			throughSurfaceVision = 0.95f;
			lizardBreedParams.biteDominance = 1f;
			lizardBreedParams.limbSize = 1.5f;
			lizardBreedParams.limbThickness = 1f;
			lizardBreedParams.stepLength = 0.8f;
			lizardBreedParams.liftFeet = 0.3f;
			lizardBreedParams.feetDown = 0.5f;
			lizardBreedParams.noGripSpeed = 0.25f;
			lizardBreedParams.limbSpeed = 9f;
			lizardBreedParams.limbQuickness = 0.8f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.smoothenLegMovement = true;
			lizardBreedParams.legPairDisplacement = 0.2f;
			lizardBreedParams.walkBob = 3f;
			lizardBreedParams.tailStiffnessDecline = 0.3f;
			lizardBreedParams.neckStiffness = 0.2f;
			lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
			lizardBreedParams.jawOpenMoveJawsApart = 23f;
			lizardBreedParams.headGraphics = new int[5];
			lizardBreedParams.framesBetweenLookFocusChange = 20;
			lizardBreedParams.tongue = true;
			lizardBreedParams.tongueAttackRange = 350f;
			lizardBreedParams.tongueWarmUp = 8;
			lizardBreedParams.tongueSegments = 10;
			lizardBreedParams.tongueChance = 0.1f;
			lizardBreedParams.baseSpeed = 10f;
			lizardBreedParams.biteDelay = 1;
			lizardBreedParams.biteDamage = 5f;
			lizardBreedParams.danger = 1f;
			lizardBreedParams.loungeDistance = 210f;
			lizardBreedParams.maxMusclePower = 14f;
			lizardBreedParams.biteHomingSpeed = 5.4f;
			lizardBreedParams.toughness = 4f;
			lizardBreedParams.stunToughness = 4f;
			lizardBreedParams.bodyMass = 13f;
			lizardBreedParams.bodySizeFac = 1.4f;
			lizardBreedParams.swimSpeed = 3f;
			lizardBreedParams.loungeSpeed = 3.2f;
			lizardBreedParams.preLoungeCrouchMovement = -0.3f;
			lizardBreedParams.loungeDelay = 60;
			lizardBreedParams.postLoungeStun = 18;
			lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 50;
			lizardBreedParams.tailSegments = 15;
			lizardBreedParams.tamingDifficulty = 10f;
			lizardBreedParams.jawOpenAngle = 150f;
			lizardBreedParams.headSize = 1.4f;
			lizardBreedParams.attemptBiteRadius = 150f;
			lizardBreedParams.tailLengthFactor = 2.5f;
			lizardBreedParams.standardColor = new Color(0.25490195f, 0f, 11f / 51f);
			lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0.5f);
			lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 0.9f);
			lizardBreedParams.tailStiffness = 400f;
			lizardBreedParams.tailColorationExponent = 1.2f;
			lizardBreedParams.tailColorationStart = 0.1f;
			lizardBreedParams.loungeTendensy = 0.2f;
		}
		CreatureTemplate creatureTemplate = new CreatureTemplate(type, lizardAncestor, list, list2, new CreatureTemplate.Relationship(CreatureTemplate.Relationship.Type.Ignores, 0f));
		creatureTemplate.breedParameters = lizardBreedParams;
		creatureTemplate.baseDamageResistance = lizardBreedParams.toughness * 2f;
		creatureTemplate.baseStunResistance = lizardBreedParams.toughness;
		creatureTemplate.damageRestistances[(int)Creature.DamageType.Bite, 0] = 2.5f;
		creatureTemplate.damageRestistances[(int)Creature.DamageType.Bite, 1] = 3f;
		creatureTemplate.meatPoints = 6;
		if (type == CreatureTemplate.Type.BlueLizard)
		{
			creatureTemplate.meatPoints = 5;
		}
		else if (type == CreatureTemplate.Type.Salamander)
		{
			creatureTemplate.waterRelationship = CreatureTemplate.WaterRelationship.Amphibious;
			if (ModManager.MMF)
			{
				creatureTemplate.canSwim = true;
			}
		}
		else if (type == CreatureTemplate.Type.GreenLizard)
		{
			creatureTemplate.wormGrassImmune = true;
			creatureTemplate.bodySize = 3f;
			creatureTemplate.meatPoints = 8;
		}
		else if (type == CreatureTemplate.Type.RedLizard || (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.TrainLizard))
		{
			creatureTemplate.damageRestistances[(int)Creature.DamageType.Explosion, 0] = 1.9f;
			creatureTemplate.bodySize = 3f;
			creatureTemplate.meatPoints = 9;
		}
		else if (type == CreatureTemplate.Type.CyanLizard)
		{
			creatureTemplate.doPreBakedPathing = false;
			creatureTemplate.preBakedPathingAncestor = blueTemplate;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.SpitLizard)
		{
			creatureTemplate.bodySize = 1f;
			creatureTemplate.meatPoints = 10;
			creatureTemplate.wormGrassImmune = true;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.ZoopLizard)
		{
			creatureTemplate.meatPoints = 2;
		}
		else if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.TrainLizard)
		{
			creatureTemplate.damageRestistances[4, 0] = 1.9f;
			creatureTemplate.bodySize = 3f;
			creatureTemplate.meatPoints = 9;
		}
		creatureTemplate.visualRadius = visualRadius;
		creatureTemplate.waterVision = waterVision;
		creatureTemplate.throughSurfaceVision = throughSurfaceVision;
		creatureTemplate.movementBasedVision = movementBasedVision;
		creatureTemplate.waterPathingResistance = waterPathingResistance;
		creatureTemplate.dangerousToPlayer = lizardBreedParams.danger;
		if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.SpitLizard)
		{
			creatureTemplate.doPreBakedPathing = false;
			creatureTemplate.preBakedPathingAncestor = greenTemplate;
		}
		else if (type != CreatureTemplate.Type.CyanLizard)
		{
			if (flag)
			{
				creatureTemplate.doPreBakedPathing = false;
				creatureTemplate.preBakedPathingAncestor = pinkTemplate;
			}
			else
			{
				creatureTemplate.doPreBakedPathing = true;
			}
		}
		creatureTemplate.virtualCreature = false;
		creatureTemplate.throwAction = "Hiss";
		creatureTemplate.pickupAction = "Bite";
		if (lizardBreedParams.tongue)
		{
			creatureTemplate.jumpAction = "Tongue";
		}
		if (type == CreatureTemplate.Type.RedLizard || (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.SpitLizard))
		{
			creatureTemplate.throwAction = "Spit";
		}
		else if (type == CreatureTemplate.Type.CyanLizard)
		{
			creatureTemplate.throwAction = "Launch";
		}
		else if (type == CreatureTemplate.Type.WhiteLizard)
		{
			creatureTemplate.throwAction = "Camouflage";
		}
		else if (type == CreatureTemplate.Type.YellowLizard)
		{
			creatureTemplate.jumpAction = "Call";
		}
		else if (lizardBreedParams.loungeTendensy >= 0.5f)
		{
			creatureTemplate.jumpAction = "Lunge";
		}
		return creatureTemplate;
	}

	public static CreatureTemplate BreedTemplate(CreatureTemplate.Type type, CreatureTemplate lizardAncestor, CreatureTemplate SalamanderTemplate)
	{
		List<TileTypeResistance> list = new List<TileTypeResistance>();
		List<TileConnectionResistance> list2 = new List<TileConnectionResistance>();
		LizardBreedParams lizardBreedParams = new LizardBreedParams(type);
		lizardBreedParams.terrainSpeeds = new LizardBreedParams.SpeedMultiplier[Enum.GetNames(typeof(AItile.Accessibility)).Length];
		for (int i = 0; i < lizardBreedParams.terrainSpeeds.Length; i++)
		{
			lizardBreedParams.terrainSpeeds[i] = new LizardBreedParams.SpeedMultiplier(1f, 0.8f, 0.7f, 1.3f);
		}
		float movementBasedVision = 0.3f;
		lizardBreedParams.terrainSpeeds[1] = new LizardBreedParams.SpeedMultiplier(1f, 1f, 1f, 1f);
		list.Add(new TileTypeResistance(AItile.Accessibility.Floor, 0.6f, PathCost.Legality.Allowed));
		lizardBreedParams.terrainSpeeds[2] = new LizardBreedParams.SpeedMultiplier((ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.EelLizard) ? 1f : 1.2f, 1f, 0.8f, 1f);
		list.Add(new TileTypeResistance(AItile.Accessibility.Corridor, 1f, PathCost.Legality.Allowed));
		lizardBreedParams.terrainSpeeds[3] = new LizardBreedParams.SpeedMultiplier(0.5f, 1f, 0.75f, 1f);
		list.Add(new TileTypeResistance(AItile.Accessibility.Climb, 0.9f, PathCost.Legality.Allowed));
		lizardBreedParams.terrainSpeeds[4] = new LizardBreedParams.SpeedMultiplier(0.9f, 1f, 1f, 1f);
		list.Add(new TileTypeResistance(AItile.Accessibility.Wall, 0.8f, PathCost.Legality.Allowed));
		lizardBreedParams.terrainSpeeds[5] = new LizardBreedParams.SpeedMultiplier(0.7f, 1f, 0.9f, 1.2f);
		list.Add(new TileTypeResistance(AItile.Accessibility.Ceiling, 1.2f, PathCost.Legality.Allowed));
		float waterPathingResistance = 0.8f;
		list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToClimb, 40f, PathCost.Legality.Allowed));
		list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToWater, 20f, PathCost.Legality.Allowed));
		list2.Add(new TileConnectionResistance(MovementConnection.MovementType.DropToFloor, 10f, PathCost.Legality.Allowed));
		lizardBreedParams.biteDelay = 3;
		lizardBreedParams.biteInFront = 10f;
		lizardBreedParams.biteHomingSpeed = 1.6f;
		lizardBreedParams.biteChance = 14f / 15f;
		lizardBreedParams.attemptBiteRadius = 800f;
		lizardBreedParams.getFreeBiteChance = 0.99f;
		lizardBreedParams.shakePrey = 90;
		lizardBreedParams.biteDamage = 0.2f;
		lizardBreedParams.biteDamageChance = 2f / 15f;
		lizardBreedParams.toughness = 0.8f;
		lizardBreedParams.stunToughness = 0.9f;
		lizardBreedParams.regainFootingCounter = 10;
		lizardBreedParams.baseSpeed = 3.75f;
		lizardBreedParams.bodyMass = 4f;
		lizardBreedParams.bodySizeFac = 0.95f;
		lizardBreedParams.bodyLengthFac = 1f;
		lizardBreedParams.bodyRadFac = 1f;
		lizardBreedParams.pullDownFac = 1f;
		lizardBreedParams.floorLeverage = 0.5f;
		lizardBreedParams.maxMusclePower = 3f;
		lizardBreedParams.wiggleSpeed = 1.3f;
		lizardBreedParams.wiggleDelay = 20;
		lizardBreedParams.bodyStiffnes = 0.7f;
		lizardBreedParams.swimSpeed = 8f;
		lizardBreedParams.idleCounterSubtractWhenCloseToIdlePos = 100;
		lizardBreedParams.danger = 0.8f;
		lizardBreedParams.aggressionCurveExponent = 0.95f;
		lizardBreedParams.headShieldAngle = 70f;
		lizardBreedParams.canExitLounge = false;
		lizardBreedParams.canExitLoungeWarmUp = false;
		lizardBreedParams.findLoungeDirection = 0.5f;
		lizardBreedParams.loungeDistance = 150f;
		lizardBreedParams.preLoungeCrouch = 30;
		lizardBreedParams.preLoungeCrouchMovement = -0.2f;
		lizardBreedParams.loungeSpeed = 1f;
		lizardBreedParams.loungeMaximumFrames = 30;
		lizardBreedParams.loungePropulsionFrames = 5;
		lizardBreedParams.loungeJumpyness = 0.5f;
		lizardBreedParams.loungeDelay = 90;
		lizardBreedParams.riskOfDoubleLoungeDelay = 0.7f;
		lizardBreedParams.postLoungeStun = 400;
		lizardBreedParams.loungeTendensy = 0.06f;
		float visualRadius = 960f;
		float waterVision = 1f;
		float throughSurfaceVision = 0.5f;
		lizardBreedParams.perfectVisionAngle = Mathf.Lerp(1f, -1f, 0f);
		lizardBreedParams.periferalVisionAngle = Mathf.Lerp(1f, -1f, 31f / 36f);
		lizardBreedParams.biteDominance = 0.2f;
		lizardBreedParams.limbSize = 1.8f;
		lizardBreedParams.limbThickness = 1f;
		lizardBreedParams.stepLength = 0.5f;
		lizardBreedParams.liftFeet = 0.3f;
		lizardBreedParams.feetDown = 0.5f;
		lizardBreedParams.noGripSpeed = 0.1f;
		lizardBreedParams.limbSpeed = 7f;
		lizardBreedParams.limbQuickness = 0.5f;
		lizardBreedParams.limbGripDelay = 1;
		lizardBreedParams.smoothenLegMovement = true;
		lizardBreedParams.legPairDisplacement = 0.3f;
		lizardBreedParams.standardColor = new Color(0f, 0.66f, 0.42f);
		lizardBreedParams.walkBob = 8f;
		lizardBreedParams.tailSegments = 16;
		lizardBreedParams.tailStiffness = 200f;
		lizardBreedParams.tailStiffnessDecline = 0.2f;
		lizardBreedParams.tailLengthFactor = 1.1f;
		lizardBreedParams.tailColorationStart = 0.9f;
		lizardBreedParams.tailColorationExponent = 2f;
		lizardBreedParams.headSize = 0.95f;
		lizardBreedParams.neckStiffness = 0.9f;
		lizardBreedParams.jawOpenAngle = 110f;
		lizardBreedParams.jawOpenLowerJawFac = 2f / 3f;
		lizardBreedParams.jawOpenMoveJawsApart = 15f;
		lizardBreedParams.headGraphics = new int[5] { 2, 2, 2, 2, 2 };
		lizardBreedParams.framesBetweenLookFocusChange = 40;
		lizardBreedParams.tongue = false;
		lizardBreedParams.tamingDifficulty = 5f;
		if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.EelLizard)
		{
			lizardBreedParams.liftFeet = 0f;
			lizardBreedParams.limbSize = 0.75f;
			lizardBreedParams.limbQuickness = 1f;
			lizardBreedParams.limbSpeed = 9f;
			lizardBreedParams.limbGripDelay = 1;
			lizardBreedParams.walkBob = 0.4f;
			lizardBreedParams.loungeTendensy = 0f;
			lizardBreedParams.biteHomingSpeed = 1f;
			lizardBreedParams.bodyRadFac = 0.5f;
		}
		CreatureTemplate creatureTemplate = new CreatureTemplate(type, lizardAncestor, list, list2, new CreatureTemplate.Relationship(CreatureTemplate.Relationship.Type.Ignores, 0f));
		creatureTemplate.breedParameters = lizardBreedParams;
		creatureTemplate.baseDamageResistance = lizardBreedParams.toughness * 2f;
		creatureTemplate.baseStunResistance = lizardBreedParams.toughness;
		creatureTemplate.damageRestistances[2, 0] = 2.5f;
		creatureTemplate.damageRestistances[2, 1] = 3f;
		creatureTemplate.meatPoints = 5;
		creatureTemplate.bodySize = 3f;
		creatureTemplate.canSwim = true;
		creatureTemplate.waterRelationship = CreatureTemplate.WaterRelationship.Amphibious;
		creatureTemplate.visualRadius = visualRadius;
		creatureTemplate.waterVision = waterVision;
		creatureTemplate.throughSurfaceVision = throughSurfaceVision;
		creatureTemplate.movementBasedVision = movementBasedVision;
		creatureTemplate.waterPathingResistance = waterPathingResistance;
		creatureTemplate.dangerousToPlayer = lizardBreedParams.danger;
		creatureTemplate.doPreBakedPathing = false;
		creatureTemplate.preBakedPathingAncestor = SalamanderTemplate;
		creatureTemplate.virtualCreature = false;
		creatureTemplate.throwAction = "Hiss";
		creatureTemplate.pickupAction = "Bite";
		if (lizardBreedParams.tongue)
		{
			creatureTemplate.jumpAction = "Tongue";
		}
		if (ModManager.MSC && type == MoreSlugcatsEnums.CreatureTemplateType.EelLizard)
		{
			creatureTemplate.bodySize = 4f;
			creatureTemplate.meatPoints = 8;
			creatureTemplate.doPreBakedPathing = false;
			creatureTemplate.waterRelationship = CreatureTemplate.WaterRelationship.Amphibious;
			creatureTemplate.canSwim = true;
		}
		return creatureTemplate;
	}
}
